### ISSUE TITLE
일괄 다운로드의 이름 포맷 설정 개선 건의합니다.

### ISSUE THREAD

**Issue by catmoodlamp** [lekakid/ArcaRefresher#1]
보통 일괄 다운로드하는 파일에 %category% 등 채널 이름, 카테고리, 게시글 이름 등을 붙이는 이유는 사진 분류의 용이함을 위해서인데, zip으로 다운로드되면 압축을 풀었을 때 이미지에 이름이 저장되지 않습니다.

크롬 확장 프로그램의 Fatkun 일괄 다운로드 이미지 를 예로 들면,  홈페이지에서 이미지를 일괄 다운로드할 때, zip으로 다운로드하지 않고 사진 하나하나를 개별 다운로드하며 순서 등을 이미지 이름에 부여합니다.
![ㅇㅇ](https://user-images.githubusercontent.com/74423490/99099457-cff85e80-261d-11eb-8595-5cac62ec17a3.gif)
이런 식으로 zip 파일에 이름을 부여하고 이미지 자체의 이름을 건들지 않는 것이 아니라, 이미지 각각의 이름에 포맷을 부여하는 기능을 넣어 주셨으면 합니다.
감사합니다.

**Comment by lekakid** [comment]
깃허브 문의는 처음이라 확인이 늦었습니다...
해당 프로그램의 동작 방식을 참고해서 반영토록 해보겠습니다.
간단하게 될거같으면 2.9.0에서 선보일듯합니다
