### ISSUE TITLE
혹시 코드 일부분

### ISSUE THREAD

**Issue by green1052** [lekakid/ArcaRefresher#102]
es2022 같은 채신 문법으로 수정하는 pr 올리면 받아주시나요??

바벨 사용하셔서 괜찮을거 같은데

**Comment by lekakid** [comment]
2020 정도 수준의 문법은 이미 사용하고 있어서 대충 다른 버전 추가 문법을 봤습니다만
바벨이 있는 이상 어차피 호환 코드로 변경될테니 성능상의 이점은 기대하기 어렵다고 생각되고
문법적으로 보기 편해진다면 고려해보겠습니다

**Comment by green1052** [comment]
넹 근데 yarn berry 사용하실 생각은 없으신가요
패키지가 많아서 너무 무거운데

**Comment by lekakid** [comment]
생각은 있습니다. 손이 아파서 거기까지 못했을 뿐이라...

**Comment by green1052** [comment]
zero install 환경으로 pr 할까요 아니면 yarn로 바꾸기만 할까요..

**Comment by lekakid** [comment]
zero install로 하죠 대충 100MB 부근일건데

**Comment by green1052** [comment]
👍
