### ISSUE TITLE
이미지 다운로드 기능 영상도 다운로드 되게 해주실 수 있나요?

### ISSUE THREAD

**Issue by green1052** [lekakid/ArcaRefresher#107]
가끔 영상 있으면 일일히 다운 받는게 귀찮아요

**Comment by green1052** [comment]
그리고 채널 자짤은 포함 안되게 해주실 수 있나요?

div#defaultImage 입니다.

**Comment by lekakid** [comment]
영상도 지원했지만 기능의 이름과 영상을 일괄다운로드할 가능성이 낮음을 감안해서 제거됐습니다.
채널 기본 이미지는 원래 빠지는걸로 기억합니다만
기본 이미지는 이미지가 첨부되면 사이트에서 제거해서 구분할 필요가 없습니다.
