### ISSUE TITLE
기능 건의

### ISSUE THREAD

**Issue by green1052** [lekakid/ArcaRefresher#11]
1. ip 정보 표기
![image](https://user-images.githubusercontent.com/34261355/135615281-782992b3-b245-4804-ac73-9051257da66a.png)

2. 게시글 목록에서 우클릭으로 미리 보기 ![image](https://user-images.githubusercontent.com/34261355/135615408-52841bc7-64b4-4835-90b9-4766aad05dd4.png)

제가 pr 해볼려고 했는데 리엑트를 모르겠네요 혹시 가능할까요?

**Comment by lekakid** [comment]
1번의 ip 정보 부분은 구체적인게 그렇게 의미가 있나 싶어서 쳐낸부분이라
보통 DIBE로 알고 있는 확장 프로그램 수준의 상세한 정보는 제공하지 않을 생각입니다

2. 지금 리액트가 매번 새 페이지에 들어갈때마다 새롭게 레이아웃을 구성하는데
이 과정이 꽤 느리기 때문에 게시물 보기에 한해서
다른 방식으로 띄우는게 더 빠른가 고민하고 있긴합니다.
만들게 된다면 올리신 모양이랑 비슷하긴 할겁니다

**Comment by green1052** [comment]
감사합니다
