### ISSUE TITLE
post option

### ISSUE THREAD

**Issue by yesyeahvh123** [lekakid/ArcaRefresher#110]
hello i see only option for user when right click, i want to known how to mark post as read, hide/block post?

**Comment by lekakid** [comment]
sorry, i checked now.
you can block posts that contain some keywords. this option exist on setting(리프레셔 설정, on site navigation)
hiding read posts not exist...

In arcalive, 'Mute(뮤트)' used to mean Block. ArcaRefresher's 'Mute' follow it.
