### ISSUE TITLE
단축키 구현 수정 요청

### ISSUE THREAD

**Issue by nanikit** [lekakid/ArcaRefresher#113]
## 맥락

아카 뷰어를 쓰시는 분이 이 스크립트를 같이 쓰면서 [아카 뷰어의 단축키가 동작하지 않는다](https://arca.live/b/simya/28534211?#c_441142947)는 제보를 했습니다.

[document 이벤트를 전부 잡아버리는 수정사항](https://github.com/lekakid/ArcaRefresher/blob/15404741ecdb529c65c5bfc22d109039b55df56b/src/feature/Site/ShortKey/Feature.jsx#L55)이 원인으로 의심되는데 이걸 제가 우회하는 건 바람직하지 않아 보여 이쪽 구현을 수정 요청드립니다.

## 재현 방법
1. [아카 뷰어를 설치](https://oo.pe/https://greasyfork.org/scripts/428230-/code/arca_viewer.user.js)합니다.
2. 아카 리프레셔 3.29.0 이상 버전을 설치합니다.
3. 이미지가 3장 이상 있는 아카라이브 페이지를 엽니다.
4. i 또는 엔터 키를 누릅니다.
5. j 또는 아래 방향키를 누릅니다.

## 기대 동작
다음 페이지로 이동합니다.

## 실제 동작
페이지가 약간 아래로 스크롤됩니다.

**Comment by lekakid** [comment]
할당 된 키만 확인하도록 조절해보겠습니다.
