### ISSUE TITLE
2가지 제안해봅니다

### ISSUE THREAD

**Issue by hotspa6** [lekakid/ArcaRefresher#115]
우선 Bing 사이트를 두 가지 방식으로 활용하는 법을 제안합니다
예1) 우측 메뉴 → Bing 검색 누름 → 기존과 같은 방식으로 검색
두번째는 우측 메뉴 Bing 사이트를 Copilot 이미지 검색으로 지원하게끔 하는 방향을 말씀드리고 싶습니다
예2) 우측 메뉴 → Bing 검색 누름 → 이미지를 Copilot 이미지 업로드로 올림 → Copilot 으로 결과 알려줌

또 단축키 목록에다 마우스 옆 버튼을 지원하면 좋을 거 같습니다

**Comment by lekakid** [comment]
Edge 브라우저에 포함된 해당 기능을 끌어다 쓰는건 구조적으로 어려울듯합니다.
단축키에 마우스 버튼을 포함하는건 우클릭 메뉴 등을 포함해서 동작 예측이 좀 어려운 부분들이 있어서 고려하고 있지 않습니다.

**Comment by hotspa6** [comment]
> Edge 브라우저에 포함된 해당 기능을 끌어다 쓰는건 구조적으로 어려울듯합니다. 
Edge 안 쓰고 아직 크롬 쓰는 사람도 있어서요 copilot 은 못 해도 Bing 사이트 추가는 한번 고려해보는 것이 어떨까요

**Comment by lekakid** [comment]
흠 고민해보겠습니다
