### ISSUE TITLE
이미지/영상 컨텍스트 메뉴 기능 켜고 끄는 옵션 추가해주세요

### ISSUE THREAD

**Issue by WolfgangKurz** [lekakid/ArcaRefresher#3]
전 브라우저 메뉴만 쓰다보니

스크립트가서 해당 코드 없애면서 쓰는데

업데이트 할 때마다 매번 가서 지워주기 불편해요

**Comment by lekakid** [comment]
옵션을 제공할 예정은 있습니다. 자꾸 까먹어서 그렇지...
2.17에 넣어보겠습니다
