### ISSUE TITLE
webpack 사용은 어떠신가요

### ISSUE THREAD

**Issue by green1052** [lekakid/ArcaRefresher#5]
https://github.com/momocow/webpack-userscript

유저 스크립트 플러그인이 있어 알려드려용

**Comment by lekakid** [comment]
음, 제가 NodeJS 개발 경험이 부족해서 정확히 이해하진 못했습니다만,
지금 번들링 모듈은 다른 NodeJS 모듈을 통합못하는게 신경쓰여서 적용 고민해보겠습니다.
프로젝트 구조 갈아엎을거 생각하면 뭔가 앞이 어둡습니다만...

**Comment by green1052** [comment]
네 
혹시 변경하실꺼면 https://nomo.asia/412 참고해보세용
