### ISSUE TITLE
GM Value들 Promise 무시됨

### ISSUE THREAD

**Issue by asdf8965** [lekakid/ArcaRefresher#6]
그리스몽키에서는 프로미스로 값이 반환됩니다.

https://wiki.greasespot.net/GM.getValue
https://wiki.greasespot.net/GM.listValues
https://wiki.greasespot.net/GM.setValue

**Comment by lekakid** [comment]
예전에 함수 스펙 차이 때문에 그리스몽키 지원을 포기했던거 같은데
저번 이슈 정리가 끝나면 호환성 검토해보겠습니다
