### ISSUE TITLE
자동 새로고침 댓글은 반영 안됨

### ISSUE THREAD

**Issue by green1052** [lekakid/ArcaRefresher#64]
글만 반영됩니다.

**Comment by lekakid** [comment]
게시물 조회수를 폭발적으로 늘리는 경향이 있어서 반영하지 않았습니다.
게시판 페이지를 따로 조회하는 방법도 있긴하지만 적용을 고려하고 있진 않습니다.

**Comment by green1052** [comment]
![Screenshot_20211126-185913_Kiwi Browser](https://user-images.githubusercontent.com/34261355/143562680-b93b2d7d-b16e-4793-81a8-8f8f559b0acc.jpg)
이게 반영이 안됩니다

**Comment by lekakid** [comment]
그건 이번에 새글이 있을때만 갱신하도록 바꿨기 때문입니다.
아카라이브 운영진의 트래픽 감소 요청이 있었습니다.

**Comment by green1052** [comment]
아 그런가요 알겠습니다

그럼 이슈는 닫겠습니다
