### ISSUE TITLE
adguard 환경에서 이미지 다운로드 안됨

### ISSUE THREAD

**Issue by green1052** [lekakid/ArcaRefresher#80]
adguard 환경에서 응답이 꺠져서 URL.createObjectURL가 작동을 안합니다

![image](https://user-images.githubusercontent.com/34261355/147365752-3e858fe0-26cc-49d8-b43e-fbf09b44aa41.png)

**Comment by lekakid** [comment]
애드가드 테스트 라이센스를 따봐야 알겠지만 responseText가 아니라 response 바이너리 데이터를 사용하기 때문에 별 상관없을거고 URL 객체가 있는지 확인해봐야 알거같습니다.

**Comment by piquark6046** [comment]
https://adguard.com/en/rewards.html
https://kb.adguard.com/en/general/userscripts
