### ISSUE TITLE
우클릭 메뉴 개선안

### ISSUE THREAD

**Issue by green1052** [lekakid/ArcaRefresher#95]
![image](https://user-images.githubusercontent.com/34261355/194823259-8513e0a9-c864-47d1-b256-bd76df22941d.png)

이미 우클릭 메뉴를 열고 다른 아카콘을 우클릭하면 이벤트가 작동하지 않습니다.
우클릭 메뉴를 다시 열기 위해서는 좌클릭을 눌러 메뉴를 닫고 다시 열어야하는데

이게 너무 귀찮습니다.

열린 상태로 우클릭을 해도 작동되게 수정해주실 수 있나요?

**Comment by green1052** [comment]
그리고 해당 우클릭 메뉴에 다운로드 혹은 클립보드로 복사 기능이 있었으면 좋겠읍니다..

**Comment by lekakid** [comment]
우클릭 메뉴 구현 편의상 화면 전체를 덮는 투명한 엘리먼트가 있는걸로 알고 있습니다. 이걸 치우면 뒷처리가 번거로워서 안했던걸로 기억합니다.

아카콘 사이즈는 작고 원본과 페이지에 뜬 이미지에 차이가 없습니다. 브라우저 메뉴를 사용 부탁드립니다.

**Comment by green1052** [comment]
엘리먼트에 덮여저있는 요소에 이벤트를 전달 할 수 있는걸로 아는데
음 많이 어렵나요..?

**Comment by lekakid** [comment]
이게... 작업 해본지 오래돼서 정확한 이유는 기억이 안나는데, 일단 해보고 다시 알려드리겠습니다.

**Comment by green1052** [comment]
넹
