### ISSUE TITLE
모듈 불러오는 로직 개선안

### ISSUE THREAD

**Issue by green1052** [lekakid/ArcaRefresher#97]
현재 모듈을 불러오는 로직은 

index.jsx -> App.jsx -> feature\index.jsx  순으로 작성 되어있습니다.

해당 방식은 직관적이지만 모듈을 추가하거나 제거한다면 일일이 코드를 수정, 삭제 해주어야하며
코드 길이 또한 같이 늘어나는 문제점을 가지고 있습니다.

현재 프로젝트에서 사용하고 있는 webpack을 사용하면 비효울적인 로직을 크게 개선할 수 있습니다.

[DCRefresher-Reborn](https://github.com/green1052/DCRefresher-Reborn/blob/main/src/index.ts#L16)

여기 제가 사용 중인 코드가 있습니다.

require.context (nodejs require 아님 @types/webpack-env 참조)를 사용해 프로젝트 폴더내 파일을 가져오고

// v는 파일 이름
context.keys().map((v: string) => context(v).default

context(v).default으로 export default한 값 가져와 모듈을 로딩합니다.

해당 방식을 이 프로젝트에 적용하면 마음이 편안해질거 같은데

어떻게 생각하시나요?

**Comment by lekakid** [comment]
안그래도 뭔가 좋은 방법이 없나 하고 있었는데 참고해보겠습니다.
